const express = require('express');
const Groq = require('groq-sdk');

const app = express();
app.use(express.json());
app.use(express.static('public'));

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

// World State
let state = {
  isPaused: false,
  budget: 10000,
  totalRevenue: 0,
  totalExpenses: 0,
  stage: "Brainstorming", // "Brainstorming", "Building", "Testing", "Launched", "Bankrupt"
  idea: "None yet (Brainstorming...)",
  progress: 0,
  productStats: {
    unitsSold: 0,
    activeUsers: 0,
    pricePerUnit: 0
  },
  employees: [
    { id: 1, name: "Alex", role: "CEO (Overconfident visionary)" },
    { id: 2, name: "Sam", role: "Dev (Stressed, pragmatic)" },
    { id: 3, name: "Maya", role: "Design (Creative perfectionist)" }
  ],
  logs: ["🏢 Office initialized. Employees starting shift..."],
  pendingInterventions: []
};

// Main AI Simulation Step
async function simulationStep() {
  if (state.isPaused || !process.env.GROQ_API_KEY) return;
  if (state.budget <= 0) {
    state.stage = "Bankrupt";
    state.logs.unshift(`[${new Date().toLocaleTimeString()}] 💥 BANKRUPT! Out of cash. God needs to inject funds!`);
    return;
  }

  const prompt = `
You are running a startup office simulation with a strict production-based economy.

CURRENT STATE:
- Budget: $${state.budget}
- Total Revenue Earned To Date: $${state.totalRevenue}
- Current Stage: ${state.stage}
- Current Startup Idea: "${state.idea}"
- Stage Progress: ${state.progress}%
- Launched Product Stats: ${JSON.stringify(state.productStats)}
- Employees: ${JSON.stringify(state.employees.map(e => `${e.name} -${e.role}`))}
${state.pendingInterventions.length ? `- GOD INTERVENTIONS JUST OCCURRED: ${state.pendingInterventions.join("; ")}` : ""}

STRICT REVENUE & COST RULES:
1. REVENUE RULE: If stage is "Brainstorming", "Building", or "Testing", revenueGenerated MUST BE EXACTLY 0. They cannot earn money before producing/launching a finished product.
2. LAUNCHED REVENUE RULE: Only if stage is "Launched", calculate revenue based on sales/users generated by their produced software/product.
3. EXPENSE RULE: Employees always spend money on servers, development tools, coffee, software licenses, or marketing ($100 to $600 per tick).

Respond strictly in valid JSON matching this schema:
{
  "log": "1-2 sentence description of what the team worked on, built, or sold.",
  "developmentExpenses": 250,
  "revenueGenerated": 0,
  "unitsSoldDelta": 0,
  "activeUsersDelta": 0,
  "ideaName": "Name of agreed startup idea (or keep current)",
  "stage": "Brainstorming" OR "Building" OR "Testing" OR "Launched",
  "progressDelta": 15
}
`;

  try {
    const completion = await groq.chat.completions.create({
      model: "openai/gpt-oss-20b",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" }
    });

    const res = JSON.parse(completion.choices[0].message.content);
    
    // Enforce strictly zero revenue if not launched
    const revenue = state.stage === "Launched" || res.stage === "Launched" ? (res.revenueGenerated || 0) : 0;
    const expenses = Math.max(0, res.developmentExpenses || 0);

    // Update Financials
    state.totalExpenses += expenses;
    state.totalRevenue += revenue;
    state.budget = Math.max(0, state.budget - expenses + revenue);

    // Update Product Stats
    if (res.unitsSoldDelta) state.productStats.unitsSold += res.unitsSoldDelta;
    if (res.activeUsersDelta) state.productStats.activeUsers = Math.max(0, state.productStats.activeUsers + res.activeUsersDelta);

    if (res.ideaName) state.idea = res.ideaName;
    if (res.stage) state.stage = res.stage;
    
    state.progress = Math.min(100, Math.max(0, state.progress + (res.progressDelta || 0)));
    if (state.progress >= 100 && state.stage === "Building") {
      state.stage = "Testing";
      state.progress = 0;
    } else if (state.progress >= 100 && state.stage === "Testing") {
      state.stage = "Launched";
      state.progress = 100;
    }

    const netText = revenue > 0 ? ` (+${revenue} rev / -${expenses} exp)` : ` (-${expenses} dev cost)`;
    state.logs.unshift(`[${new Date().toLocaleTimeString()}] ${res.log}${netText}`);
    if (state.logs.length > 30) state.logs.pop();

    state.pendingInterventions = [];
  } catch (err) {
    console.error("AI Step Error:", err.message);
  }
}

// Tick every 15 seconds
setInterval(simulationStep, 15000);

// API Routes
app.get('/api/state', (req, res) => res.json(state));

app.post('/api/admin/toggle-pause', (req, res) => {
  state.isPaused = !state.isPaused;
  state.logs.unshift(`[⚡ GOD MODE] Simulation ${state.isPaused ? 'PAUSED' : 'RESUMED'}`);
  res.json({ isPaused: state.isPaused });
});

app.post('/api/admin/add-cash', (req, res) => {
  const amount = req.body.amount || 5000;
  state.budget += amount;
  state.logs.unshift(`[⚡ GOD MODE] Injected $${amount} into office bank account!`);
  res.json({ budget: state.budget });
});

app.post('/api/admin/hire', (req, res) => {
  const { name, role } = req.body;
  if (name && role) {
    state.employees.push({ id: Date.now(), name, role });
    state.pendingInterventions.push(`God hired a new employee: ${name} (${role})`);
    state.logs.unshift(`[⚡ GOD MODE] Hired ${name} as ${role}!`);
    res.json({ success: true });
  } else {
    res.status(400).json({ error: "Missing name or role" });
  }
});

app.post('/api/admin/command', (req, res) => {
  const { command } = req.body;
  if (!command) return res.status(400).json({ error: "No command provided" });

  state.pendingInterventions.push(command);
  state.logs.unshift(`[⚡ GOD EVENT] ${command}`);
  res.json({ success: true });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
